### ISSUE TITLE
Membrane Potential: Context Responses (Interactive Description)

### ISSUE THREAD

**Issue by terracoda** [phetsims/membrane-transport#239]
Follow-up to #166, the Membrane Potential Radio Group is working well with Alternative Input and firing Accessible Names, and associated PDOM info. Accessible Help Text is also good.

Now for Context Responses, here's my plan from the design document:

![Image](https://github.com/user-attachments/assets/b705acec-627e-490e-906f-60a20c97dae6)
 

### Context Responses:
**From -70 to -50:**
- Sodium Ion Voltage-gated, open

**From -70 to +30:**
- Potassium Ion Voltage-gated, open. 

**From -50 to +30:** - Possibly 3 responses?
- Potassium Ion Voltage-gated, open. Sodium Ion, closed.
- Potassium Ion Voltage-gated, open. 
- Sodium Ion, closed.

**From +30 to -50:** - Possibly 3 responses?
- Sodium Ion Voltage-gated, open. Potassium Ion, closed.
- Sodium Ion Voltage-gated, open.
- Potassium Ion, closed.

**From +30 to -70 or From -50 to -70:**
- Voltage-gated channel{{s}}, closed. 

**Change in Membrane Potential + no change in membrane:**
- No change in transport proteins. 

Question:
- How to manage the presence of all or only one Voltage-gated channel.

**Comment by terracoda** [comment]
In above commenthttps://github.com/phetsims/membrane-transport/issues/239#issue-3157190669 I added a few cases not in the design doc and added the question about how to handle this.

**Comment by jessegreenberg** [comment]
I think the way to not have these as context responses for the radio buttons, but to add them to an alerter that watches all changes to the Membrane that need to be described.

**Comment by samreid** [comment]
We will capture snapshots of relevant state in MembraneTransportModel.step, and signify significant changes via accessible responses `addAccessibleResponse` in MembraneTransportView. Note this is more complex since a protein may be added or removed between steps. This will allow us to aggregate multiple similar events. We will be able to scale this up to cover active transport proteins if needed.  I'll work on this.

**Comment by samreid** [comment]
I've got this fixed in my working copy, but will probably commit tomorrow when I can keep a closer eye on CT

**Comment by samreid** [comment]
Implement above. I tried to achieve a balance between correctness and simplicity, and hence the strings are not identical to the design above.  But it is designed in a way that is easy to adjust. The current YAML is:

```yaml
  # Membrane potential change responses for voltage-gated channels
  membranePotentialChanges:
    sodiumVoltageGatedOpened: Sodium Ion Voltage-gated, opened.
    sodiumVoltageGatedClosed: Sodium Ion Voltage-gated, closed.
    potassiumVoltageGatedOpened: Potassium Ion Voltage-gated, opened.
    potassiumVoltageGatedClosed: Potassium Ion Voltage-gated, closed.
    sodiumOpenedPotassiumOpened: "{ a11y.membranePotentialChanges.sodiumVoltageGatedOpened } { a11y.membranePotentialChanges.potassiumVoltageGatedOpened }"
    sodiumOpenedPotassiumClosed: "{ a11y.membranePotentialChanges.sodiumVoltageGatedOpened } { a11y.membranePotentialChanges.potassiumVoltageGatedClosed }"
    sodiumClosedPotassiumOpened: "{ a11y.membranePotentialChanges.sodiumVoltageGatedClosed } { a11y.membranePotentialChanges.potassiumVoltageGatedOpened }"
    sodiumClosedPotassiumClosed: "{ a11y.membranePotentialChanges.sodiumVoltageGatedClosed } { a11y.membranePotentialChanges.potassiumVoltageGatedClosed }"
    noChange: No change in transport proteins.
```

@terracoda can you please review in the a11y view and see if you recommend any changes? After @terracoda comments on the design, I will address the adjustments, if any, then we will request review from @jessegreenberg
